wc -w llda_train_input/hot_cores_2_features.dat
wc -w llda_train_input/hot_cores_full_features.dat
wc -w llda_train_input/hot_cores_full_expanded_00010_features.dat
wc -w llda_train_input/extragalactic_2_features.dat
wc -w llda_train_input/hot_cores_tr_features.dat
wc -w llda_train_input/dark_clouds_full_features.dat
wc -w llda_train_input/alma_band_6_full_features.dat
wc -w llda_train_input/extragalactic_full_expanded_00002_features.dat
wc -w llda_train_input/extragalactic_full_expanded_00010_features.dat
wc -w llda_train_input/hot_cores_full_expanded_00002_features.dat
wc -w llda_train_input/dark_clouds_full_expanded_00002_features.dat
wc -w llda_train_input/extragalactic_full_features.dat
wc -w llda_train_input/alma_band_6_tr_features.dat
wc -w llda_train_input/dark_clouds_full_expanded_00010_features.dat
wc -w llda_train_input/alma_band_6_full_expanded_00002_features.dat
wc -w llda_train_input/dark_clouds_tr_features.dat
wc -w llda_train_input/extragalactic_tr_features.dat
wc -w llda_train_input/dark_clouds_2_features.dat
wc -w llda_train_input/alma_band_6_full_expanded_00010_features.dat
wc -w llda_train_input/alma_band_6_2_features.dat
wc -w llda_train_input/diffuse_clouds_full_features.dat
wc -w llda_train_input/comets_full_expanded_00010_features.dat
wc -w llda_train_input/comets_tr_features.dat
wc -w llda_train_input/comets_2_features.dat
wc -w llda_train_input/diffuse_clouds_full_expanded_00010_features.dat
wc -w llda_train_input/diffuse_clouds_tr_features.dat
wc -w llda_train_input/diffuse_clouds_full_expanded_00002_features.dat
wc -w llda_train_input/comets_full_expanded_00002_features.dat
wc -w llda_train_input/comets_full_features.dat
wc -w llda_train_input/diffuse_clouds_2_features.dat
wc -w llda_train_input/planetary_tr_features.dat
wc -w llda_train_input/planetary_full_expanded_00010_features.dat
wc -w llda_train_input/planetary_2_features.dat
wc -w llda_train_input/planetary_full_features.dat
wc -w llda_train_input/planetary_full_expanded_00002_features.dat