0 Methylidyne
1 Butyronitrile
2 Formaldehyde
3 Sulfur dioxide
4 Carbon Monoxide
5 Water
6 Chloronium
7 Imidogen
8 Thioformylium
9 Mercapto radical
10 Methyl formate vt01
11 Methyliumylidene
12 Cyanide Radical
13 Hydroxyl
14 Nitric oxide
15 Cyclopropenylidene
16 Silicon Monoxide
17 Hydrogen Cyanide
18 Carbon Monosulfide
19 Hydrogen sulfide
20 Molecular oxygen
21 Hydrogen Isocyanide
22 Formylium
23 Sulfoniumylidene
